SELECT * FROM "MEMBER";

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
       'admin01@kh.or.kr',
       '$2a$10$mQuTt31FyF3uXL2qAkF21eZsPnoQP6zeo9pKCevmsWtGJEOsKtFhu',
       '김관리',
       '01098765432',
       NULL,
       NULL,
       DEFAULT,
       DEFAULT,
       2
);

COMMIT;

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_PW, AUTHORITY
FROM "MEMBER"
WHERE MEMBER_EMAIL = 'admin01@kh.or.kr'
	AND MEMBER_DEL_FL = 'N'
	AND AUTHORITY = 2;

-- 241212 수업 중 SQL문 확인

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'Y'
ORDER BY MEMBER_NO DESC;

UPDATE "MEMBER"
SET MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 5
	AND MEMBER_DEL_FL = 'N';
	
COMMIT;

SELECT * FROM "MEMBER";

SELECT * FROM "BOARD";

SELECT b.BOARD_NO, bt.BOARD_NAME, b.BOARD_TITLE, m.MEMBER_NICKNAME 
FROM "BOARD" b
JOIN BOARD_TYPE bt ON(b.BOARD_CODE = bt.BOARD_CODE)
JOIN "MEMBER" m on(b.MEMBER_NO = m.MEMBER_NO)
WHERE BOARD_DEL_FL = 'Y';